apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: docker.io/nhqb3197/aws_rag_chatbot_ai
    newName: docker.io/nhqb3197/aws_rag_chatbot_ai
    newTag: latest
