apiVersion: v1
kind: Service
metadata:
  name: aws-rag-chatbot-svc
  labels:
    app: aws-rag-chatbot
  annotations:
    # create an NLB and expose it to the Internet
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
spec:
  selector:
    app: aws-rag-chatbot
  ports:
    - name: http-frontend
      port: 3000
      targetPort: http-frontend
  type: LoadBalancer