apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181
  username: root
  insecure: "true"